server:
  port: 8761
  context-path: /eureka-server

spring:
  application:
    name: eureka-server
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.201.207.54：8762/eureka/
    healthcheck:
      enabled: true