server:
  context-path: /config-server
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maoerd/configuration
          cloneOnStart: true
          force-pull: true
          searchPaths: '{application}'

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://35.185.131.60:8761/eureka-server/eureka/